[project]
name = "pybites-summer-nasa-gallery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "nicegui>=2.21.1",
]
